equinor/semeio

ci/jenkins/Jenkinsfile-komodo
ci/jenkins/testkomodo.sh
test_requirements.txt

Create jenkins test for semeio to komodo

Komodo test semeio

---

semeio/jobs/correlated_observations_scaling/exceptions.py
semeio/jobs/correlated_observations_scaling/scaled_matrix.py
semeio/jobs/spearman_correlation_job/job.py
tests/jobs/spearman_correlation_job/test_integration.py
tests/jobs/spearman_correlation_job/unit/test_spearman_job.py

Fix semeio 23

---

ci/jenkins/testkomodo.sh

Prevent the test from removing libres test-data

Move tests to new folder for komodo-testing

---

.travis.yml
semeio/jobs/config_workflow_jobs/CSV_EXPORT2
semeio/jobs/csv_export2/csv_export2.py
semeio/jobs/scripts/csv_export2.py
setup.py
tests/hook_implementations/test_hook_implementations.py
tests/jobs/csv_export2/conftest.py
tests/jobs/csv_export2/test_integration.py

Reimplemented CSV_EXPORT1 (as "CSV_EXPORT2") using fmu.ensemble.
https://equinor.github.io/fmu-ensemble/advancedusage.html#merging-data

Proof-of-concept CSV_EXPORT1 reimplementation

---

semeio/jobs/rft/trajectory.py
tests/jobs/rft/test_gendata_rft.py

Fix TrajectoryPoint (gendata_rft) representation

---

semeio/jobs/design_kw/design_kw.py
tests/jobs/design_kw/test_design_kw.py

Ref. error reported on slack ert-users.
This will only improve the error message.

Improve error message to user from DESIGN_KW

---

semeio/communication/__init__.py
semeio/communication/semeio_script.py
semeio/jobs/correlated_observations_scaling/job.py
semeio/jobs/correlated_observations_scaling/scaled_matrix.py
semeio/jobs/scripts/correlated_observations_scaling.py
tests/communication/test_integration.py
tests/communication/unit/test_semeio_script.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/correlated_observations_scaling/unit/test_scaled_matrix.py
tests/jobs/correlated_observations_scaling/unit/test_scaling_job.py

Resolves #112 
Use new reporter in semeio.communications for `reporting` data.

Convert COS job to SemeioScript and use reporter for exporting data

---

semeio/jobs/config_workflow_jobs/MISFIT_PREPROCESSOR
semeio/jobs/misfit_preprocessor/__init__.py
semeio/jobs/misfit_preprocessor/config.py
semeio/jobs/misfit_preprocessor/exceptions.py
semeio/jobs/misfit_preprocessor/job.py
semeio/jobs/scripts/misfit_preprocessor.py
semeio/jobs/spearman_correlation_job/job.py
tests/hook_implementations/test_hook_implementations.py
tests/jobs/misfit_preprocessor/test_integration.py
tests/jobs/misfit_preprocessor/test_misfit_preprocessor.py
tests/jobs/misfit_preprocessor/unit/test_config.py

Resolves: https://github.com/equinor/semeio/issues/68
**Misson of the PR**
- Establish the user interface of the observation correlation tooling that is to pushed out in the company as described in #68.
- Add a bigger test base to ensure that results are as expected. In particular I've mocked parts of the `MeasuredData` structure from `ERT`, which allows me to quickly evaluate thousands of forward models without depending on libres.
**Remaining work for this PR**
- Find a better name for the workflow. The idea of `AUTO_CORRELATE_OBSERVATIONS` was that it would be semi-automatic. However, this is a very overloaded term in statistics, so we should call it something else. Perhaps `SCALE_OBSERVATION_CLUSTERS`?
**Remaining work**
- Write documentation. I've started filling out the schema. Will …

Misfit preprocessor

---

semeio/jobs/correlated_observations_scaling/job_config.py
tests/jobs/correlated_observations_scaling/unit/test_config.py

I've shamefully copied content from https://github.com/equinor/semeio/pull/77 and added it to the description of the schema. Furthermore the schema should then either be added using the generate rst function, or using the sphinx extension from config suite.
The tests have been slightly restructured as well, one test removed (`invalid_too_short_index_list`, as it did not test what was expected, outdated), and added one more for required keys.
Currently one test is failing because there are multiple errors when adding a negative value in the index list. The second error, which shouldn't be there, is:
`"'Will go through the input and try to convert to list of int' failed on input '[-1, 2, 3]' with error 'invalid literal for int() with base 10: '''"`
Not clear how to handle the last error …

Update tests and description

---

semeio/communication/reporter.py
semeio/jobs/misfit_preprocessor/job.py
semeio/jobs/scripts/misfit_preprocessor.py
semeio/jobs/scripts/spearman_correlation.py
semeio/jobs/spearman_correlation_job/job.py
setup.py
tests/communication/unit/test_file_reporter.py
tests/jobs/misfit_preprocessor/test_misfit_preprocessor.py
tests/jobs/spearman_correlation_job/test_integration.py

Spearman to semeioscript

---

semeio/jobs/correlated_observations_scaling/job.py
semeio/jobs/correlated_observations_scaling/job_config.py
setup.py
tests/jobs/correlated_observations_scaling/unit/test_config.py
tests/jobs/correlated_observations_scaling/unit/test_obs_util.py
tests/jobs/correlated_observations_scaling/unit/test_scaling_job.py
tox.ini

The one that bugs me a bit is the change in user feedback when `MK.Required` is not used:
From: `'Missing key: CALCULATE_KEYS'`
To: `Section length must be greater than 0 is false on input '()'`
I could have made context validators, but issues are:
- has to be fairly hacky to facilitate every section that will be validated
- made unique context validator for each container that must be validated.

Updated configsuite

---

semeio/jobs/scripts/design2params.py
semeio/jobs/scripts/design_kw.py
semeio/jobs/scripts/gendata_rft.py

Adjust documentation for RST formatting

---

setup.py

Let's use the little known tool called `find_packages`

Use find_packages in setup

---

semeio/jobs/design2params/design2params.py
tests/jobs/design2params/test_design2params.py

This did not crash in the Py2 ert_statoil version
Anticipating future crash, exit cleanly if defaults sheet
only contain one column.

Fix crash on design matrices with empty defaults sheet.

---

semeio/communication/semeio_script.py
semeio/jobs/correlated_observations_scaling/job.py
semeio/jobs/misfit_preprocessor/config.py
semeio/jobs/rft/gendata_rft.py
semeio/jobs/scripts/correlated_observations_scaling.py
semeio/jobs/scripts/design2params.py
semeio/jobs/scripts/design_kw.py
semeio/jobs/scripts/fm_pyscal.py
semeio/jobs/scripts/misfit_preprocessor.py
tests/communication/test_integration.py
tests/communication/unit/test_file_reporter.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/correlated_observations_scaling/unit/test_config.py
tests/jobs/correlated_observations_scaling/unit/test_obs_util.py
tests/jobs/correlated_observations_scaling/unit/test_scaling_job.py
tests/jobs/design2params/test_design2params.py
tests/jobs/misfit_preprocessor/test_integration.py
tests/jobs/misfit_preprocessor/test_misfit_preprocessor.py
tests/jobs/misfit_preprocessor/unit/test_config.py
tests/jobs/nosim/test_nosim.py

Going from black 19.10b0 to 20.8b0, black will modify the source code.
Could potentially pin the black version in CI setup.

Blacken with black 20.8b0

---

semeio/jobs/config_workflow_jobs/SPEARMAN_CORRELATION
semeio/jobs/scripts/spearman_correlation.py
setup.py
tests/hook_implementations/test_hook_implementations.py

Document spearman correlation through plugin system

---

semeio/jobs/config_workflow_jobs/MISFIT_PREPROCESSOR
semeio/jobs/scripts/misfit_preprocessor.py
setup.py
tests/hook_implementations/test_hook_implementations.py

Add documentation to black_box_job

---

semeio/jobs/config_workflow_jobs/CORRELATED_OBSERVATIONS_SCALING
semeio/jobs/correlated_observations_scaling/job_config.py
semeio/jobs/scripts/correlated_observations_scaling.py
setup.py
tests/hook_implementations/test_hook_implementations.py
tests/jobs/correlated_observations_scaling/test_integration.py

This PR will use the ert plugin system to add the schema to the ert documentation and move away for registering with the old config file.

Document correlated scaling job through plugin system

---

semeio/communication/semeio_script.py
tests/communication/test-data/test_workflow_job.py
tests/communication/unit/test_semeio_script.py

Fixes #104 
The approach is described in the issue.

Filter out records not of this thread

---

semeio/workflows/correlated_observations_scaling/cos.py
test_requirements.txt
tests/jobs/correlated_observations_scaling/unit/test_examples.py

Most of what was suggesten in: https://github.com/equinor/semeio/pull/77 has already been implemented in https://github.com/equinor/semeio/pull/124 This PR takes the examples from #77 and passes them to `ert` through the plugin system.
Closes #9

Give examples of cos usage through plugin system

---

semeio/workflows/correlated_observations_scaling/job.py
semeio/workflows/correlated_observations_scaling/scaled_matrix.py
tests/jobs/correlated_observations_scaling/unit/test_scaled_matrix.py

Refactor scaling factor calculation

---

semeio/communication/semeio_script.py
tests/communication/test_integration.py
tests/communication/unit/test_semeio_script.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/spearman_correlation_job/test_integration.py

Solves #136 
The report folder is added to the storage folder of ert. This comes with
the issue that it is regarded as an actual case in the eyes of ERT. ~By
hiding the folder we avoid the issue.~

Move report folder

---

semeio/jobs/scripts/csv_export2.py
semeio/jobs/scripts/design2params.py
semeio/jobs/scripts/design_kw.py
semeio/jobs/scripts/fm_pyscal.py
semeio/jobs/scripts/fm_stea.py
semeio/jobs/scripts/gendata_rft.py

Add shebang to scripts

---

tests/conftest.py

Do garbage collection after tests to avoid storage pollution in root

---

semeio/workflows/misfit_preprocessor/config.py
semeio/workflows/misfit_preprocessor/exceptions.py
semeio/workflows/misfit_preprocessor/job.py
semeio/workflows/misfit_preprocessor/misfit_preprocessor.py
semeio/workflows/spearman_correlation_job/job.py
tests/jobs/misfit_preprocessor/test_integration.py
tests/jobs/misfit_preprocessor/test_misfit_preprocessor.py
tests/jobs/misfit_preprocessor/unit/test_assemble_config.py

Add observations filtering option to MPP

---

semeio/jobs/rft/gendata_rft.py
tests/jobs/rft/test_write_pressure.py

Fix bug when writing no pressure points

---

semeio/__init__.py

Closes #122 
I would like to add tests, but not sure where. 
I looked for tests for the valid_file function, but did not find any.
Are tests like the ones in ert expectedm e.g.?
```
def test_version_valid_Version(capsys):
try:
ert_parser(None, ["--version"])
except SystemExit as e:
assert e.code == 0
ert_version, _ = capsys.readouterr()
ert_version = ert_version.rstrip("\n")
assert Version(ert_version)
def test_version_mocked(capsys, monkeypatch):
monkeypatch.setattr(ert_shared, "__version__", "1.0.3")
try:
ert_parser(None, ["--version"])
except SystemExit as e:
assert e.code == 0
ert_version, _ = capsys.readouterr()
ert_version = ert_version.rstrip("\n")
assert ert_version == "1.0.3"
```

Add semeio.__version__

---

semeio/workflows/csv_export2/csv_export2.py
tests/jobs/csv_export2/conftest.py
tests/jobs/csv_export2/test_integration.py

Solves #187 
Builds on PR #220

[csv_export2] Fix crash on missing parameters.txt

---

.github/workflows/testing.yml

Update deprecated commands in GitHub Actions

---

.github/workflows/testing.yml

Add test runs on MacOS

---

semeio/jobs/design2params/design2params.py
tests/jobs/design2params/test_design2params.py

Disallow whitespace in parameter names in design2params

---

semeio/jobs/design2params/design2params.py
tests/jobs/design2params/test_design2params.py

Improve warning message pointing to empty cells
Solves #234 and #235

Allow missing values in other realizations than current.

---

semeio/jobs/design2params/design2params.py
tests/jobs/design2params/test_design2params.py

Deny certain parameters in design2params

---

.github/workflows/publish_to_pypi.yml

This PR adds a GitHub workflow for publishing to PyPi

Add deploy to PyPi workflow

---

semeio/workflows/misfit_preprocessor/config.py

Closes #58, blocked by: https://github.com/equinor/ert/pull/1044

Add docs about recommended hook

---

.github/workflows/testing.yml
MANIFEST.in
README.md
pyproject.toml
semeio/communication/semeio_script.py
semeio/workflows/csv_export2/csv_export2.py
semeio/workflows/misfit_preprocessor/misfit_preprocessor.py
semeio/workflows/spearman_correlation_job/spearman_correlation.py
setup.py
tests/jobs/nosim/test_nosim.py
tests/test_ert_integration.py
tox.ini

Add pypi libres

---

semeio/jobs/scripts/fm_pyscal.py

Adapted from: https://wiki.equinor.com/wiki/index.php/Pyscal

Add pyscal fm model docs from wiki

---

semeio/workflows/misfit_preprocessor/config.py

There is no key called `PRE_FIRST_ANALYSYS`

Fix wrong hook key

---

semeio/workflows/csv_export2/csv_export2.py

Add weekly to csv_export2 docs

---

semeio/jobs/rft/trajectory.py
semeio/jobs/scripts/gendata_rft.py
tests/jobs/rft/test_gendata_rft.py
tests/jobs/rft/test_trajectory.py

Add trajectory file error handling to entry point

---

semeio/workflows/misfit_preprocessor/config.py

Fix misfit_preprocessor docstring

---

semeio/workflows/misfit_preprocessor/config.py

Document the different workflow options

---

semeio/_exceptions/exceptions.py
semeio/jobs/design2params/design2params.py
semeio/jobs/scripts/design2params.py
setup.py
tests/jobs/design2params/test_design2params.py

Bump pandas

---

pyproject.toml
setup.py

Unfix segyio

---

semeio/jobs/overburden_timeshift/ots.py
semeio/jobs/overburden_timeshift/ots_config.py
tests/jobs/overburden_timeshift/test_ots_config.py

Check eclfile

---

semeio/jobs/design2params/design2params.py

Fix switch from xlrd to openpyxl as engine in pandas

---

semeio/workflows/misfit_preprocessor/config.py
semeio/workflows/misfit_preprocessor/job.py
tests/jobs/misfit_preprocessor/test_integration.py
tests/jobs/misfit_preprocessor/test_misfit_preprocessor.py
tests/jobs/misfit_preprocessor/unit/test_config.py

Add linkage

---

semeio/jobs/scripts/fm_pyscal.py
semeio/jobs/scripts/fm_stea.py
semeio/jobs/scripts/overburden_timeshift.py

Equinor prefers british spelling over american.

Change modeling to modelling in docs

---

semeio/jobs/scripts/fm_pyscal.py
tests/jobs/pyscal/test_pyscal.py

Add tailor-made error message for specific user input error

---

.pylintrc
tests/jobs/correlated_observations_scaling/unit/test_config.py

Created an issue for fixing this properly here: https://github.com/equinor/semeio/issues/299

Pylint update

---

semeio/communication/semeio_script.py
tests/communication/test_integration.py
tests/communication/unit/test_semeio_script.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/spearman_correlation_job/test_integration.py

Closes #210, though the issue is phrased as a question, so should consider other options.

Change output folder from config name to case name

---

semeio/jobs/scripts/fm_pyscal.py

Related to issue https://github.com/equinor/pyscal/issues/247
This documentation fix is valid regardless of the outcome of that issue.

Fix bug in pyscal usage docs

---

semeio/communication/semeio_script.py
tests/communication/unit/test_semeio_script.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/spearman_correlation_job/test_integration.py

Move reporter output to output path

---

semeio/jobs/scripts/fm_stea.py
tests/jobs/stea/test_stea.py

Dump full stea response

---

semeio/jobs/scripts/gendata_rft.py

Some minor addition/changes to the rest of the doc

Add OUTPUTDIRECTORY to doc example, gendata_rft

---

tests/jobs/overburden_timeshift/test_ots.py
tests/jobs/overburden_timeshift/test_ots_integration.py
tests/jobs/overburden_timeshift/test_ots_velocity.py

There was a mix of folders with and without init files in the test subdirectory, this adds to the missing for consistency.

Add init files in test folders

---

semeio/workflows/ahm_analysis/ahmanalysis.py

This is to correct the ahm_analysis workflow description for the output path of the created csv files.

Correct ahm_analysis workflow description

---

semeio/communication/semeio_script.py
semeio/workflows/ahm_analysis/ahmanalysis.py
semeio/workflows/misfit_preprocessor/misfit_preprocessor.py
semeio/workflows/misfit_preprocessor/workflow_config.py
tests/communication/test_integration.py
tests/communication/unit/test_semeio_script.py
tests/jobs/ahm_analysis/test_integration.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/spearman_correlation_job/test_integration.py

Change output dir for reports

---

semeio/_docs_utils/_json_schema_2_rst.py
semeio/communication/semeio_script.py
semeio/workflows/csv_export2/csv_export2.py
semeio/workflows/misfit_preprocessor/misfit_preprocessor.py
setup.py
tests/docs_utils/test_json_schema_2_rst.py
tests/jobs/ahm_analysis/test_ahm_analysis.py
tests/jobs/ahm_analysis/test_integration.py
tests/jobs/csv_export2/test_integration.py
tests/jobs/misfit_preprocessor/test_integration.py
tests/jobs/pyscal/test_pyscal.py
tests/jobs/rft/test_gendata_rft.py
tests/jobs/rft/test_trajectory.py
tests/legacy_test_data/failed_runs_in_storage/jobs/aggregator.py
tests/legacy_test_data/failed_runs_in_storage/jobs/perlin.py

Closes #325
There are alternatives to implementing something new, and I would really like to do that, except I can not find any existing good solution. There is `jsonschema2rst`, but the only documented entry point is from the command line:
```python
import tempfile
import subprocess
import json
import os
with tempfile.TemporaryDirectory() as tmpdirname:
with open(os.path.join(tmpdirname, "json_schema.json"), "w") as fout:
json.dump(schema, fout)
subprocess.call(
["jsonschema2rst", tmpdirname, os.path.join(tmpdirname, "result")]
)
with open(os.path.join(tmpdirname, "result", "json_schema.rst"), "r") as fin:
rst_result = fin.read()
```
This _could_ work (or we could call the internal parser in `jsonschema2rst`, but is not documented). Though the vanilla result from this is not valid rst, …

Add documentation from json schema

---

.pylintrc
semeio/jobs/overburden_timeshift/ots.py
semeio/jobs/overburden_timeshift/ots_config.py
semeio/jobs/rft/gendata_rft.py
semeio/jobs/rft/trajectory.py
semeio/jobs/rft/utility.py
semeio/workflows/correlated_observations_scaling/cos.py
semeio/workflows/misfit_preprocessor/misfit_preprocessor.py
setup.py
tests/communication/test_integration.py
tests/communication/unit/test_file_reporter.py
tests/communication/unit/test_semeio_script.py
tests/jobs/csv_export2/conftest.py
tests/jobs/csv_export2/test_integration.py
tests/jobs/design2params/test_design2params.py
tests/jobs/design_kw/test_design_kw.py
tests/jobs/misfit_preprocessor/test_integration.py
tests/jobs/nosim/test_nosim.py
tests/jobs/overburden_timeshift/test_ots.py
tests/jobs/overburden_timeshift/test_ots_config.py
tests/jobs/overburden_timeshift/test_ots_integration.py
tests/jobs/rft/conftest.py
tests/jobs/rft/test_gendata_rft.py
tests/jobs/rft/test_write_simdata.py
tests/jobs/spearman_correlation_job/test_integration.py
tests/jobs/stea/test_stea.py
tests/legacy_test_data/failed_runs_in_storage/jobs/aggregator.py
tests/legacy_test_data/snake_oil/jobs/snake_oil_npv.py
tests/test_ert_integration.py

Replace surface

---

semeio/workflows/localisation/local_config_script.py
semeio/workflows/localisation/local_script_lib.py
semeio/workflows/localisation/localisation_config.py
semeio/workflows/localisation/localisation_debug_settings.py
setup.py
test_requirements.txt
tests/hook_implementations/test_hook_implementations.py
tests/jobs/conftest.py
tests/jobs/localisation/test_configs/test_config.py
tests/jobs/localisation/test_configs/test_field_config.py
tests/jobs/localisation/test_configs/test_obs_config.py
tests/jobs/localisation/test_configs/test_parameters.py
tests/jobs/localisation/test_integration.py

A first version of the workflow script to specify localisation from a configuration file. 
This PR covers parameters of type:
- scalar parameters specified by ERT keyword GEN_KW   (Parameters of form  nodename;parametername)
- scalar parameters specified by ERT keyword GEN_PARAM  (Parameters of form nodename:index
- field parameters specified by ERT keyword FIELD              (Nodename)
- field parameters specified by ERT keyword SURFACE        (Nodename)
For parameters of type FIELD or SURFACE, there is an option to specify scaling of correlations using a scaling factor.
Implemented scaling functions depends on distance from reference point (typically observation localisation). The currently implemented functions are:
- Gaussian decay from a reference point
- Exponential decay from a …

Add localisation mvp

---

semeio/workflows/localisation/local_config_script.py
tests/jobs/localisation/test_valid_rst.py

Add user documentation with example for the first version of the LOCALISATION_JOB.

Add documentation for first version

---

tests/jobs/csv_export2/test_integration.py

Assert message in log file

---

semeio/jobs/overburden_timeshift/ots.py

Return early to avoid writing empty folder

---

semeio/workflows/ahm_analysis/ahmanalysis.py
semeio/workflows/correlated_observations_scaling/obs_utils.py
semeio/workflows/correlated_observations_scaling/update_scaling.py
setup.py
tests/jobs/localisation/test_integration.py

Update to adhere to ert change

---

ci/jenkins/testkomodo.sh
tests/conftest.py
tests/jobs/rft/test_gendata_rft.py

First step towards having a proven  reference example for GENDATA_RFT documentation.
There should possibly be some more asserts that ERT is able to internalize, but I don't know how.
Next step is to try more advanced setups with RFT's at different wellpoints at different dates. Ping @rnyb

Add test function for gendata_rft ert integration

---

semeio/workflows/ahm_analysis/ahmanalysis.py
semeio/workflows/localisation/local_script_lib.py

Adapting to new API after local_dataset was removed

---

semeio/jobs/config_jobs/REPLACE_STRING_CONFIG
semeio/jobs/scripts/replace_string.py
tests/hook_implementations/test_hook_implementations.py
tests/jobs/replace_string/test_integration.py

Add replace string job using sed

---

semeio/workflows/localisation/local_config_script.py
setup.py

Update documentation of localisation job with some missing information.

Update documentation for the localisation job with some missing information

---

semeio/jobs/config_jobs/REPLACE_STRING_CONFIG
semeio/jobs/scripts/replace_string.py
setup.py
tests/jobs/replace_string/test_integration.py

Add simple WYSIWYG replace_string script

---

semeio/workflows/correlated_observations_scaling/obs_utils.py
setup.py
tests/jobs/correlated_observations_scaling/test_integration.py

Observations were required only for validation of keys.

Adjust to ert api change

---

tests/jobs/csv_export2/test_integration.py

Find ert log file

---

semeio/workflows/spearman_correlation_job/job.py
tests/jobs/correlated_observations_scaling/unit/test_scaling_job.py

This is a private method defined in ERT and should not be tested here.

Remove test of _filter_on_column_index

---

test_requirements.txt
tests/docs_utils/test_json_schema_2_rst.py
tests/jobs/correlated_observations_scaling/unit/test_examples.py
tests/jobs/csv_export2/test_integration.py
tests/jobs/localisation/test_valid_rst.py

Upgrade from rstcheck 5.*.* to rstcheck-core

---

semeio/communication/semeio_script.py
semeio/workflows/correlated_observations_scaling/obs_utils.py
semeio/workflows/csv_export2/csv_export2.py
semeio/workflows/localisation/local_script_lib.py
setup.py
tests/jobs/localisation/test_configs/test_config.py
tests/jobs/spearman_correlation_job/test_integration.py

This uses private import ert._c_wrappers, which should be fixed asap. However, this temporary fix should do for now.

Move to new ert import structure

---

semeio/jobs/design_kw/design_kw.py
semeio/jobs/scripts/design_kw.py
tests/jobs/design_kw/test_design_kw_entry.py

Plus some drive-by cleaning and typing.
Resolves #456

Raise SystemExit when templates are unmatched

---

.gitignore
tests/jobs/stea/test_integration.py

Use subprocess to launch ert instead of main()

---

.github/workflows/actionlint.yml
.github/workflows/style.yml

Testing https://github.com/rhysd/actionlint

Add actionlint to lint the workflow files

---

semeio/workflows/csv_export2/csv_export2.py

Resolves #473 
See also issue #474.

Document the bug in csv_export2 on year 2262

---

ci/jenkins/testkomodo.sh
tests/jobs/conftest.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/csv_export2/conftest.py
tests/jobs/csv_export2/test_integration.py
tox.ini

Rewrite csv_export tests to use a mocked set
Solves #330 
Solves #449 
Solves #329 
Solves #482 
~Leftover cleaning put into #482~

Remove all traces of ert-statoil testdata

---

semeio/jobs/rft/gendata_rft.py

Optimize finding ijk from xyz in grid

---

semeio/workflows/ahm_analysis/ahmanalysis.py
setup.py
tests/jobs/ahm_analysis/test_integration.py

Pending: https://github.com/equinor/ert/pull/4522

Update to new  ERT api for run context

---

semeio/workflows/correlated_observations_scaling/scaled_matrix.py
semeio/workflows/misfit_preprocessor/job.py
tests/jobs/correlated_observations_scaling/test_integration.py
tests/jobs/correlated_observations_scaling/unit/test_scaled_matrix.py
tests/jobs/misfit_preprocessor/test_misfit_preprocessor.py

Code returns one more principal component than it should.
I've added a property test and fixed failing tests.

Return correct number of principal components

---

semeio/workflows/ahm_analysis/ahmanalysis.py
tests/jobs/ahm_analysis/test_ahm_analysis.py

Closes https://github.com/equinor/semeio/issues/504

Read field property directly

---

semeio/jobs/design2params/design2params.py
semeio/workflows/localisation/local_script_lib.py
tests/jobs/design2params/test_design2params.py

Solve compatibility with Pandas 2.0.0 and ERT 5.0.0

---

semeio/workflows/localisation/local_script_lib.py
setup.py

Update Semeio to use refactored gen_kw_nodes in Ert.
Ref.
https://github.com/equinor/ert/issues/5267

Use GenKwConfig in place of EnkfConfigNode

---

semeio/workflows/ahm_analysis/ahmanalysis.py
semeio/workflows/correlated_observations_scaling/cos.py
semeio/workflows/localisation/local_config_script.py
semeio/workflows/misfit_preprocessor/misfit_preprocessor.py
semeio/workflows/spearman_correlation_job/spearman_correlation.py

Avoid using get_observation_key by num

---

semeio/workflows/localisation/local_script_lib.py

This PR was triggered by a change in Ert, -- namely the removal of ErtImplType.

Replace ErtImplType

---

semeio/workflows/ahm_analysis/ahmanalysis.py
setup.py

This due to breaking change in ert

Use load_parameters instead of load_field

---

semeio/workflows/localisation/local_script_lib.py

Remove active_index_for_parameter

---

semeio/workflows/localisation/local_script_lib.py
tests/jobs/localisation/test_methods.py

Pylint complains about duplicate code.

Build decay object in separate function

---

.github/workflows/testing.yml
pyproject.toml
tox.ini

Add support for Python 3.11

---

.github/workflows/typing.yml
.mypy.ini
pyproject.toml
semeio/jobs/design_kw/design_kw.py
semeio/jobs/scripts/design_kw.py
semeio/workflows/ahm_analysis/ahmanalysis.py
semeio/workflows/localisation/localisation_config.py

Replace conlist etc with Annotated and Field
to make mypy happy.
**NB**
Notice that I have set quite a few of the checks to `False` in `mypy.ini`, which means that this does not do a lot of type-checking yet.
The goal is to eventually set all of them to `True`.

Introduce mypy

---

semeio/workflows/localisation/local_script_lib.py

Purpose: Prepare for typing by having class definitions at top of the file.

Moved some class definitions up to top of the file

---

ci/testkomodo.sh

Ensure ci testing does not pull semeio from pypi

---

.github/workflows/testing.yml
tests/forward_models/rft/test_gendata_rft.py

just running tests on main

---

pyproject.toml
tox.ini

Remove dev artifact from tox.ini

---

pyproject.toml
src/semeio/communication/semeio_script.py
tests/communication/unit/test_semeio_script.py
tests/workflows/ahm_analysis/test_integration.py

Breaking changes in: https://github.com/equinor/ert/commit/3f3e682156516d15ccded659adefb3730da43e83

Update to new ert api

---

src/semeio/forward_models/__init__.py
src/semeio/forward_models/scripts/design2params.py
src/semeio/forward_models/scripts/design_kw.py
src/semeio/forward_models/scripts/fm_pyscal.py
src/semeio/forward_models/scripts/gendata_rft.py
src/semeio/forward_models/scripts/overburden_timeshift.py
src/semeio/forward_models/scripts/replace_string.py
src/semeio/hook_implementations/forward_models.py
tests/hook_implementations/test_hook_implementations.py

Move forward model docs to plugins

---

tests/forward_models/rft/test_gendata_rft.py

Part of https://github.com/equinor/ert/issues/8348

Adjust NUM_REALIZATIONS=2 in tests running ensemble smoother

---

pyproject.toml
src/semeio/forward_models/__init__.py
src/semeio/forward_models/design_kw/design_kw.py
src/semeio/forward_models/scripts/design_kw.py
tests/communication/test_integration.py
tests/conftest.py
tests/forward_models/design_kw/test_design_kw.py
tests/forward_models/replace_string/test_integration.py
tests/test_ert_integration.py
tests/workflows/ahm_analysis/test_ahm_analysis.py
tests/workflows/ahm_analysis/test_integration.py

Add `validate_pre_experiment`-method to DESIGN_KW forward model

---

pyproject.toml
tests/workflows/ahm_analysis/test_ahm_analysis.py

To make it work w/ parquet PR on ERT: https://github.com/equinor/ert/pull/8684

Update observation keys getter

---

src/semeio/fmudesign/_designsummary.py
src/semeio/fmudesign/_excel2dict.py
src/semeio/fmudesign/_tornado_onebyone.py
src/semeio/fmudesign/create_design.py
src/semeio/forward_models/__init__.py
src/semeio/forward_models/design2params/design2params.py
src/semeio/forward_models/design_kw/design_kw.py
src/semeio/forward_models/overburden_timeshift/ots.py
src/semeio/forward_models/overburden_timeshift/ots_vel_surface.py
src/semeio/forward_models/rft/zonemap.py
src/semeio/forward_models/scripts/gendata_rft.py

Fix typos in code

---

src/semeio/fmudesign/create_design.py

Older numpy versions return "w" and not "eigenvalues".

Use tuple indexing to get eigenvalues

---

src/semeio/forward_models/__init__.py
tests/forward_models/nosim/test_nosim.py

Fix INSERT_NOSIM and REMOVE_NOSIM on OS X

---

pyproject.toml
src/semeio/fmudesign/iman_conover.py
src/semeio/workflows/ahm_analysis/ahmanalysis.py

Goes along with https://github.com/equinor/ert/pull/10586

Adapt to polars for esupdate

---

pyproject.toml
src/semeio/workflows/ahm_analysis/ahmanalysis.py
tests/workflows/ahm_analysis/test_ahm_analysis.py

https://github.com/equinor/ert/pull/10709

Adapt to restructuring of ERT outlier settings

---

src/semeio/workflows/ahm_analysis/ahmanalysis.py
tests/workflows/ahm_analysis/test_integration.py

Fix bug where there was a name collision with tmp_storage

---

src/semeio/fmudesign/create_design.py

**Question:** What does `background` mean in this context? Is it related to "background parameters"?

Fix docstring of add_seeds

---

.pre-commit-config.yaml
pyproject.toml
src/semeio/fmudesign/_designsummary.py
src/semeio/fmudesign/_excel2dict.py
src/semeio/fmudesign/_tornado_onebyone.py
src/semeio/fmudesign/create_design.py
src/semeio/fmudesign/design_distributions.py
src/semeio/fmudesign/fmudesignrunner.py
src/semeio/fmudesign/iman_conover.py
src/semeio/forward_models/rft/trajectory.py
tests/fmudesign/test_iman_conover.py

This PR adds type annotations mainly to the function/method signatures of the `fmudesign` module. In some cases, some type annotations in the body is added. 
I have really no knowledge of this repo, so please feel free to correct me if i made any mistakes :)

Add type annotations to `semeio.fmudesign`

---

src/semeio/fmudesign/design_distributions.py
tests/fmudesign/test_design_distributions.py

Breaking-change - Remove support for setting high=low in triangle

---

tests/fmudesign/test_create_design.py

We currently have a snapshot test that catches any changes in random sampling. This is fine and good, but arguably misses the more important point: statistical properties should not change. In the future if we change RNG, we will now be able to tell if (1) the change is equivalent to changing a random seed or (2) the change actually changes the statistical properties.

Test statistical properties

---

src/semeio/workflows/ahm_analysis/ahmanalysis.py

to accomodate new param configs

Adapt to new scalar parameter setup
